[book]
authors = ["Lefteris Lazaropoulos, Zoe Paraskevopoulou, Anja Petkovic Komel, Sophie Rain, dxo"]
language = "en"
src = "src"
title = "The Act Book"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true
copy-js = true
line-numbers = true
