[book]
authors = ["dxo"]
language = "en"
src = "src"
title = "The Act Book"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true
[preprocessor.katex]
after = ["links"]
optional = true

[output]
[output.html]
additional-js =["mermaid.min.js", "mermaid-init.js"]
